import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

import { readInlined, root } from './inline-sources.mjs'

/**
 * Build the installable package the profile mounts, as opposed to the dynamic Cordis
 * Package the development loop uses.
 *
 * Two artifacts come out of one source tree:
 *
 * - `lib/index.js` — the Host half. A profile row has to exist for the browser roster to
 *   see the package at all (`client-modules` scans the Host Loader's rows for packages
 *   declaring `dsh.client`), and this half is what that row imports. It contributes
 *   nothing: every decision is a client decision.
 * - `lib/client.js` — the browser half, served as a classic script at
 *   `/plugins/<name>/client.js`. It only *registers* a factory with the page's module
 *   loader; the factory returns the Cordis plugin months later, when the shell
 *   materializes the entry. It is a single self-contained file: the runner's `React`
 *   builtin becomes `require('react')` (a client baseline module), and the runner's
 *   `styles` builtin becomes a `<style>` element this bundle owns.
 */

/** Registration id of the client bundle; must equal the package name the row mounts. */
const ENTRY_ID = 'deepseek-peaks'

/** Services the client plugin needs before `apply` may run. */
const INJECT = ['timer', 'slots']

/** Header on generated files, so nobody edits a build artifact by hand. */
const GENERATED_NOTE = '// GENERATED by tools/build-package.mjs — edit src/ and run `npm run build`.\n'

/**
 * The browser-half wrapper: module-loader registration, the DOM stylesheet owner, and
 * the `apply`/`inject` exports the Cordis client loader expects from a plugin bundle.
 */
function browserWrapper({ core, client }) {
  return `${GENERATED_NOTE}
window.__ModuleLoader__.load({
  id: ${JSON.stringify(ENTRY_ID)},
  factory: (require) => {
    var module = { exports: {} }
    var exports = module.exports

    const React = require("react")

    /**
     * Own the plugin's stylesheet. A browser bundle has DOM access — unlike a dynamic
     * Package, which is handed the runner's \`styles\` builtin — so the styles live in one
     * <style> element tagged as ours, which is how the module loader attributes and
     * disposes injected CSS.
     */
    function createStyles() {
      let element = null
      return {
        insert(css) {
          if (element === null) {
            element = document.createElement('style')
            element.setAttribute('data-plugin', ${JSON.stringify(ENTRY_ID)})
            element.setAttribute('data-plugin-css', ${JSON.stringify(ENTRY_ID)})
            document.head.append(element)
          }
          element.textContent += css
          return () => {
            if (element === null) return
            element.remove()
            element = null
          }
        },
      }
    }

    function apply(ctx) {
      return createPlugin({ styles: createStyles() }).apply(ctx)
    }

// ─── src/peaks-core.mjs ─────────────────────────────────────────────────────────────
${core}
// ─── src/client.mjs ─────────────────────────────────────────────────────────────────
${client}
// ─── package entry ──────────────────────────────────────────────────────────────────
    exports.apply = apply
    exports.inject = ${JSON.stringify(INJECT)}
    return module.exports
  },
})
`
}

/**
 * Build both artifacts in memory.
 * @returns the two file contents plus their digests.
 */
export function buildPackage() {
  const { core, client } = readInlined()
  const host = `${GENERATED_NOTE}${readFileSync(join(root, 'src', 'host.mjs'), 'utf8')}`
  const browser = browserWrapper({ core, client })

  if (/^import\s/m.test(`${core}\n${client}`) || /^export\s/m.test(`${core}\n${client}`)) {
    throw new Error('the inlined sources still contain an import or export statement')
  }
  // The browser bundle is a classic script: it may only reach platform singletons
  // (baseline modules) and its own scope, so validate it the way the page will run it.
  const required = [...browser.matchAll(/require\((['"])([^'"]+)\1\)/g)].map((match) => match[2])
  const unsupported = required.filter((specifier) => specifier !== 'react')
  if (unsupported.length > 0) {
    throw new Error(`the browser bundle requests modules outside the client baseline: ${unsupported.join(', ')}`)
  }
  new Function(browser)

  const digest = (text) => createHash('sha256').update(text).digest('hex').slice(0, 12)
  return {
    files: [
      { path: 'lib/index.js', text: host },
      { path: 'lib/client.js', text: browser },
    ],
    required,
    digests: { host: digest(host), browser: digest(browser) },
  }
}

/**
 * Write both artifacts.
 * @returns the written paths and digests.
 */
export function writePackage() {
  const built = buildPackage()
  for (const file of built.files) {
    mkdirSync(dirname(join(root, file.path)), { recursive: true })
    writeFileSync(join(root, file.path), file.text)
  }
  return built
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  const built = writePackage()
  for (const file of built.files) {
    console.log(`${join(root, file.path)} — ${Buffer.byteLength(file.text)} bytes`)
  }
  console.log(`digests: host ${built.digests.host}, browser ${built.digests.browser}`)
}
