import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Build the self-contained plain-JavaScript body of the dynamic Cordis Client Package
 * from the two modules that hold the real source.
 *
 * A dynamic Package is a function body: it cannot `import`, so `src/peaks-core.mjs` is
 * inlined and the `react` import is dropped in favour of the runner's `React` builtin.
 * Keeping one source of truth matters here — the repository package and the running
 * dynamic Package must be the same logic, and the tests exercise this exact output.
 *
 * @returns the generated body text.
 */

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..')

/** Remove ESM import statements, which a dynamic body cannot contain. */
function stripImports(source) {
  return source.replace(/^import\s[\s\S]*?from\s+'[^']+'\s*$/gm, '')
}

/** Turn `export const/function` into plain declarations; this body has no exports. */
function stripExports(source) {
  return source.replace(/^export\s+/gm, '')
}

/**
 * Drop comment-only lines. A dynamic body is transcribed by hand into `cordis_define`,
 * so the runtime artifact stays lean while the repository sources keep their docs.
 * Only lines that *begin* a comment are removed, so a `//` inside a string (the rule's
 * source URL) survives untouched.
 */
function stripCommentLines(source) {
  const kept = []
  let inBlock = false
  for (const line of source.split('\n')) {
    const trimmed = line.trim()
    if (inBlock) {
      if (trimmed.includes('*/')) inBlock = false
      continue
    }
    if (trimmed.startsWith('/*')) {
      if (!trimmed.includes('*/')) inBlock = true
      continue
    }
    if (trimmed.startsWith('//')) continue
    kept.push(line)
  }
  return kept.join('\n')
}

/**
 * The shipped tail, and the development tail that additionally wires the diagnostic sink
 * to the Host (`PEAKS_REPORT=1`). The shipped body must not carry a channel it never
 * uses; the seam itself stays in `src/client.mjs`, inert without a `report`.
 */
const TAILS = {
  shipped: `
// The dynamic runner provides \`styles\` as a builtin; the diagnostic sink stays unwired.
return createPlugin({ styles })
`,
  reporting: `
// The dynamic runner provides \`styles\` and \`host\` as builtins.
return createPlugin({ styles, report: (payload) => { host.call('report', payload).catch(() => {}) } })
`,
}

export function buildDynamicBody({ report = process.env.PEAKS_REPORT === '1' } = {}) {
  const core = stripCommentLines(stripExports(readFileSync(join(root, 'src', 'peaks-core.mjs'), 'utf8')))
  const client = stripCommentLines(stripExports(stripImports(readFileSync(join(root, 'src', 'client.mjs'), 'utf8'))))
  const body = `// GENERATED by tools/dynamic-body.mjs from src/peaks-core.mjs and src/client.mjs.\n${core}\n${client}\n${report ? TAILS.reporting : TAILS.shipped}`

  if (/^import\s/m.test(body) || /^export\s/m.test(body)) {
    throw new Error('generated body still contains an import or export statement')
  }
  // The runner evaluates the body inside `new Function`; fail here rather than in the browser.
  new Function('React', 'host', 'styles', 'console', body)
  return body
}

export function writeDynamicBody(relativePath = 'tmp/dynamic-client-body.js', options) {
  const body = buildDynamicBody(options)
  const out = join(root, relativePath)
  writeFileSync(out, body)
  const digest = createHash('sha256').update(body).digest('hex').slice(0, 12)
  return { body, out, digest, bytes: Buffer.byteLength(body) }
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  const { out, digest, bytes } = writeDynamicBody()
  console.log(`${out}\n${bytes} bytes, sha256:${digest}`)
}
