import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { readInlined, root } from './inline-sources.mjs'

/**
 * Build the self-contained plain-JavaScript body of the dynamic Cordis Client Package
 * from the two modules that hold the real source.
 *
 * A dynamic Package is a function body: it cannot `import`, so `src/peaks-core.mjs` is
 * inlined and the `react` import is dropped in favour of the runner's `React` builtin.
 * Keeping one source of truth matters here — the repository package and the running
 * dynamic Package must be the same logic, and the tests exercise this exact output.
 *
 * `tools/build-package.mjs` inlines the same two sources into the browser bundle of the
 * installable package; this file is the development-time twin.
 *
 * @returns the generated body text.
 */

/**
 * The shipped tail, and the development tail that additionally wires the diagnostic sink
 * to the Host (`PEAKS_REPORT=1`). The shipped body must not carry a channel it never
 * uses; the seam itself stays in `src/client.mjs`, inert without a `report`.
 */
const TAILS = {
  shipped: `
// The dynamic runner provides \`styles\` as a builtin; the diagnostic sink stays unwired.
return createPlugin({ styles })
`,
  reporting: `
// The dynamic runner provides \`styles\` and \`host\` as builtins.
return createPlugin({ styles, report: (payload) => { host.call('report', payload).catch(() => {}) } })
`,
}

export function buildDynamicBody({ report = process.env.PEAKS_REPORT === '1' } = {}) {
  const { core, client } = readInlined({ stripComments: true })
  const body = `// GENERATED by tools/dynamic-body.mjs from src/peaks-core.mjs and src/client.mjs.\n${core}\n${client}\n${report ? TAILS.reporting : TAILS.shipped}`

  if (/^import\s/m.test(body) || /^export\s/m.test(body)) {
    throw new Error('generated body still contains an import or export statement')
  }
  // The runner evaluates the body inside `new Function`; fail here rather than in the browser.
  new Function('React', 'host', 'styles', 'console', body)
  return body
}

export function writeDynamicBody(relativePath = 'tmp/dynamic-client-body.js', options) {
  const body = buildDynamicBody(options)
  const out = join(root, relativePath)
  writeFileSync(out, body)
  const digest = createHash('sha256').update(body).digest('hex').slice(0, 12)
  return { body, out, digest, bytes: Buffer.byteLength(body) }
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
  const { out, digest, bytes } = writeDynamicBody()
  console.log(`${out}\n${bytes} bytes, sha256:${digest}`)
}
